version: '3.1'
services:

  frontend:
    build:
      context: ../frontend
      args:
        - REACT_APP_API_URL=localhost:8080
    ports:
      - '3000:80'
    depends_on:
      - backend

  backend:
    image: backend:1.0
    environment:
      MYSQL_HOST: db
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    build: 
      context: backend/db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: demo
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
