version: '3.1'
services:

  frontend:
    image: frontend:1.0
    environment: 
      REACT_APP_API_SERVER: backend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    image: backend:1.0
    environment:
      MYSQL_HOST: db
      CORS_FRONTEND: frontend
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    build: 
      context: backend/db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: demo
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
